# filepath: /Users/viljarpartel/Desktop/test/_config.yml
title: My Jekyll Site
description: A simple Jekyll site
baseurl: "/test" # the subpath of your site, e.g. /blog
url: "https://alger116.github.io/hanked" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-redirect-from